#!/bin/bash

exec 2>&1

export JAVA_HOME=$(hab pkg path core/jdk8)
export TOMCAT_HOME="{{pkg.svc_var_path}}/tc"
export CATALINA_OPTS="{{cfg.server.catalina-opts}}"

exec chpst -u hab:hab ${TOMCAT_HOME}/bin/catalina.sh run
